// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: chat_server.proto

package chat_server_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageInfo) Reset() {
	*x = SendMessageInfo{}
	mi := &file_chat_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageInfo) ProtoMessage() {}

func (x *SendMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageInfo.ProtoReflect.Descriptor instead.
func (*SendMessageInfo) Descriptor() ([]byte, []int) {
	return file_chat_server_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageInfo) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendMessageInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_chat_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_chat_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_chat_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_chat_server_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_chat_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_chat_server_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SendMessageInfo       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_server_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetInfo() *SendMessageInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_chat_server_proto protoreflect.FileDescriptor

const file_chat_server_proto_rawDesc = "" +
	"\n" +
	"\x11chat_server.proto\x12\x0echat_server_v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n" +
	"\x0fSendMessageInfo\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"-\n" +
	"\rCreateRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x12SendMessageRequest\x123\n" +
	"\x04info\x18\x01 \x01(\v2\x1f.chat_server_v1.SendMessageInfoR\x04info2\xe3\x01\n" +
	"\fChatServerV1\x12G\n" +
	"\x06Create\x12\x1d.chat_server_v1.CreateRequest\x1a\x1e.chat_server_v1.CreateResponse\x12?\n" +
	"\x06Delete\x12\x1d.chat_server_v1.DeleteRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\vSendMessage\x12\".chat_server_v1.SendMessageRequest\x1a\x16.google.protobuf.EmptyBGZEgithub.com/obeismo/chat_server/grpc/pkg/chat_server/v1;chat_server_v1b\x06proto3"

var (
	file_chat_server_proto_rawDescOnce sync.Once
	file_chat_server_proto_rawDescData []byte
)

func file_chat_server_proto_rawDescGZIP() []byte {
	file_chat_server_proto_rawDescOnce.Do(func() {
		file_chat_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_server_proto_rawDesc), len(file_chat_server_proto_rawDesc)))
	})
	return file_chat_server_proto_rawDescData
}

var file_chat_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chat_server_proto_goTypes = []any{
	(*SendMessageInfo)(nil),       // 0: chat_server_v1.SendMessageInfo
	(*CreateRequest)(nil),         // 1: chat_server_v1.CreateRequest
	(*CreateResponse)(nil),        // 2: chat_server_v1.CreateResponse
	(*DeleteRequest)(nil),         // 3: chat_server_v1.DeleteRequest
	(*SendMessageRequest)(nil),    // 4: chat_server_v1.SendMessageRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_chat_server_proto_depIdxs = []int32{
	5, // 0: chat_server_v1.SendMessageInfo.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: chat_server_v1.SendMessageRequest.info:type_name -> chat_server_v1.SendMessageInfo
	1, // 2: chat_server_v1.ChatServerV1.Create:input_type -> chat_server_v1.CreateRequest
	3, // 3: chat_server_v1.ChatServerV1.Delete:input_type -> chat_server_v1.DeleteRequest
	4, // 4: chat_server_v1.ChatServerV1.SendMessage:input_type -> chat_server_v1.SendMessageRequest
	2, // 5: chat_server_v1.ChatServerV1.Create:output_type -> chat_server_v1.CreateResponse
	6, // 6: chat_server_v1.ChatServerV1.Delete:output_type -> google.protobuf.Empty
	6, // 7: chat_server_v1.ChatServerV1.SendMessage:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_server_proto_init() }
func file_chat_server_proto_init() {
	if File_chat_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_server_proto_rawDesc), len(file_chat_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_server_proto_goTypes,
		DependencyIndexes: file_chat_server_proto_depIdxs,
		MessageInfos:      file_chat_server_proto_msgTypes,
	}.Build()
	File_chat_server_proto = out.File
	file_chat_server_proto_goTypes = nil
	file_chat_server_proto_depIdxs = nil
}
